language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - evm list
  - evm use $EVM_EMACS
  - evm bin
  - which emacs
  - emacs --version
  - cask upgrade-cask
  - cask --debug

env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-git-snapshot-travis

script:
  - emacs --version
  - make test